"""
referentiel.py — Référentiel des notions et de leurs compétences

Sans dépendance au client LLM, pour que le seed puisse le lire sans clé.
"""

REFERENTIEL = {
    "analyse_dimensionnelle": {
        "notion_nom": "Analyse dimensionnelle",
        "competences": [
            {
                "code": "ad01",
                "nom": "Distinguer dimension et unité",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ad02",
                "nom": "Connaître les 7 grandeurs fondamentales du SI",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ad03",
                "nom": "Règles de calcul sur les dimensions",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ad04",
                "nom": "Règles de calcul sur les puissances en contexte dimensionnel",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ad05",
                "nom": "Établir la dimension d'une grandeur dérivée",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ad06",
                "nom": "Convertir unité dérivée en unités de base",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ad07",
                "nom": "Vérifier l'homogénéité d'une formule",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ad08",
                "nom": "Déduire la dimension d'une grandeur inconnue",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "ad09",
                "nom": "Identifier les paramètres pertinents en modélisation",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "ad10",
                "nom": "Résoudre une équation aux dimensions par identification d'exposants",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "ad11",
                "nom": "Interpréter physiquement le résultat",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "ad12",
                "nom": "Connaître et utiliser les constantes fondamentales",
                "niveau": "solide",
                "score": 0.0,
            },
        ],
    },
    "fractions_puissances_radicaux": {
        "notion_nom": "Fractions – Puissances – Radicaux",
        "competences": [
            {
                "code": "fp01",
                "nom": "Opérations élémentaires sur les fractions",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp02",
                "nom": "Choisir un dénominateur commun pertinent",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp03",
                "nom": "Simplifier une fraction numérique et littérale",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp04",
                "nom": "Manipuler les fractions composées",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp05",
                "nom": "Respecter les priorités opératoires",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp06",
                "nom": "Connaître les définitions et conventions des puissances",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp07",
                "nom": "Appliquer les règles de calcul sur les puissances",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp08",
                "nom": "Manipuler les puissances avec exposants littéraux",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp09",
                "nom": "Factoriser une expression contenant des puissances",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp10",
                "nom": "Décomposer une base en facteurs premiers",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp11",
                "nom": "Gérer les signes dans les puissances",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp12",
                "nom": "Connaître les propriétés fondamentales de la racine carrée",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "fp13",
                "nom": "Simplifier une expression contenant des racines",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp14",
                "nom": "Rationaliser un dénominateur",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "fp15",
                "nom": "Articuler racines, puissances et identités remarquables",
                "niveau": "expert",
                "score": 0.0,
            },
        ],
    },
    "logarithme_exponentielle": {
        "notion_nom": "Logarithme et exponentielle",
        "competences": [
            {
                "code": "le01",
                "nom": "Définition et propriétés caractéristiques de l'exponentielle",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "le02",
                "nom": "Règles algébriques sur l'exponentielle",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "le03",
                "nom": "Dériver une expression contenant une exponentielle",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le04",
                "nom": "Résoudre une équation avec exponentielles",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le05",
                "nom": "Résoudre une inéquation avec exponentielles",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le06",
                "nom": "Définition et propriétés caractéristiques du logarithme népérien",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "le07",
                "nom": "Règles algébriques sur le logarithme népérien",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "le08",
                "nom": "Dériver une expression contenant un logarithme",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le09",
                "nom": "Identifier le domaine de définition d'un logarithme",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le10",
                "nom": "Résoudre une équation avec logarithmes",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le11",
                "nom": "Résoudre une inéquation avec logarithmes",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le12",
                "nom": "Utiliser les identités fondamentales entre exponentielle et logarithme",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "le13",
                "nom": "Convertir entre forme exponentielle et logarithmique",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "le14",
                "nom": "Manipuler la fonction exponentielle de base a",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "le15",
                "nom": "Manipuler le logarithme décimal",
                "niveau": "solide",
                "score": 0.0,
            },
        ],
    },
    "manipulation_expressions_litterales": {
        "notion_nom": "Manipulation d'expressions littérales",
        "competences": [
            {
                "code": "el01",
                "nom": "Distinguer expression littérale et application numérique",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el02",
                "nom": "Identifier la variable à isoler et anticiper la stratégie",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el03",
                "nom": "Appliquer le principe d'équivalence des opérations",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el04",
                "nom": "Suivre l'ordre inverse des priorités opératoires",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el05",
                "nom": "Isoler une variable au numérateur d'une fraction",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el06",
                "nom": "Isoler une variable au dénominateur",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el07",
                "nom": "Faire passer un terme additif",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el08",
                "nom": "Faire passer un facteur multiplicatif",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el09",
                "nom": "Factoriser pour simplifier lors d'un isolement",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el10",
                "nom": "Distribuer pour développer",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "el11",
                "nom": "Éliminer un carré par passage à la racine",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el12",
                "nom": "Éliminer une racine par élévation au carré",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el13",
                "nom": "Éliminer une exponentielle ou un logarithme",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el14",
                "nom": "Manipuler les sommes et produits remarquables",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el15",
                "nom": "Isoler dans une expression de la forme (ax+b)/(cx+d)=k",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el16",
                "nom": "Isoler une variable apparaissant à plusieurs endroits",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "el17",
                "nom": "Manipuler une fraction étagée",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "el18",
                "nom": "Substituer une expression dans une autre",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el19",
                "nom": "Combiner plusieurs relations",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "el20",
                "nom": "Transposer une structure par analogie",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "el21",
                "nom": "Gérer les conditions d'existence et de validité",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "el22",
                "nom": "Vérifier la cohérence dimensionnelle ou un cas particulier",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "el23",
                "nom": "Maintenir une notation rigoureuse",
                "niveau": "solide",
                "score": 0.0,
            },
        ],
    },
    "equations_inequations": {
        "notion_nom": "Équations – Inéquations",
        "competences": [
            {
                "code": "ei01",
                "nom": "Comprendre le vocabulaire des équations",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei02",
                "nom": "Tester si un nombre est solution",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei03",
                "nom": "Traduire un problème simple en équation",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei04",
                "nom": "Résoudre une équation du premier degré simple",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei05",
                "nom": "Résoudre une équation du premier degré avec inconnue des deux côtés",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei06",
                "nom": "Développer et réduire avant de résoudre",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei07",
                "nom": "Résoudre une équation-produit",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei08",
                "nom": "Résoudre une équation de la forme x² = a",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei09",
                "nom": "Résoudre une équation-quotient avec valeurs interdites",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei10",
                "nom": "Résoudre une inéquation du premier degré",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei11",
                "nom": "Représenter les solutions d'une inéquation",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "ei12",
                "nom": "Étudier le signe d'une expression affine",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei13",
                "nom": "Résoudre une inéquation-produit ou quotient avec tableau de signes",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei14",
                "nom": "Résoudre une équation du second degré avec le discriminant",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "ei15",
                "nom": "Résoudre une inéquation du second degré",
                "niveau": "expert",
                "score": 0.0,
            },
        ],
    },
    "polynomes_factorisation": {
        "notion_nom": "Polynômes – Factorisation",
        "competences": [
            {
                "code": "pf01",
                "nom": "Reconnaître un polynôme et ses éléments",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf02",
                "nom": "Déterminer le degré d'un polynôme",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf03",
                "nom": "Réduire et ordonner un polynôme",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf04",
                "nom": "Développer une expression polynomiale",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf05",
                "nom": "Utiliser les identités remarquables",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf06",
                "nom": "Factoriser par facteur commun simple ou composé",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "pf07",
                "nom": "Factoriser par regroupement",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "pf08",
                "nom": "Factoriser un trinôme du second degré",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "pf09",
                "nom": "Calculer le discriminant",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf10",
                "nom": "Déterminer les racines d'un trinôme",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "pf11",
                "nom": "Relier racines et factorisation",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "pf12",
                "nom": "Vérifier qu'un nombre est racine",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "pf13",
                "nom": "Factoriser un polynôme de degré 3 avec racine évidente",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "pf14",
                "nom": "Utiliser les identités de degré 3",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "pf15",
                "nom": "Développer avec le binôme de Newton",
                "niveau": "expert",
                "score": 0.0,
            },
        ],
    },
    "trigonometrie": {
        "notion_nom": "Trigonométrie",
        "competences": [
            {
                "code": "tr01",
                "nom": "Comprendre la notion d'angle en radian",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "tr02",
                "nom": "Convertir degrés et radians",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "tr03",
                "nom": "Connaître les valeurs remarquables de sinus et cosinus",
                "niveau": "basique",
                "score": 1.0,
            },
            {
                "code": "tr04",
                "nom": "Lire un angle sur le cercle trigonométrique",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr05",
                "nom": "Déterminer une mesure principale d'un angle",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr06",
                "nom": "Reconnaître deux angles équivalents modulo 2π",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr07",
                "nom": "Comprendre les fonctions sinus, cosinus et tangente",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr08",
                "nom": "Utiliser les relations fondamentales entre sinus, cosinus et tangente",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr09",
                "nom": "Étudier la parité de sinus, cosinus et tangente",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr10",
                "nom": "Utiliser les angles associés",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr11",
                "nom": "Calculer des valeurs exactes avec angles remarquables",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr12",
                "nom": "Calculer des valeurs non immédiates par décomposition",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr13",
                "nom": "Manipuler correctement la tangente et ses conditions d'existence",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr14",
                "nom": "Connaître et appliquer les formules d'addition",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr15",
                "nom": "Connaître et appliquer les formules de duplication",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr16",
                "nom": "Résoudre des équations trigonométriques simples",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr17",
                "nom": "Résoudre des équations avec angle composé",
                "niveau": "solide",
                "score": 0.0,
            },
            {
                "code": "tr18",
                "nom": "Résoudre des équations nécessitant une transformation",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "tr19",
                "nom": "Résoudre des inéquations trigonométriques",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "tr20",
                "nom": "Linéariser des puissances trigonométriques simples",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "tr21",
                "nom": "Transformer des produits en sommes",
                "niveau": "expert",
                "score": 0.0,
            },
            {
                "code": "tr22",
                "nom": "Transformer des sommes en produits",
                "niveau": "expert",
                "score": 0.0,
            },
        ],
    },
}
